### ISSUE TITLE
Remove flow header annotation

### ISSUE THREAD

**Issue by meandmax** [zxbodya/flowts#25]
I was looking for the code that removes `@flow` in order to support `@flow strict` and `@flow strict-local`. Could you point me into the right direction. Have a hard time finding the right spot.

**Comment by zxbodya** [comment]
Sure - it is in [`Program` visitor in babel-flow-to-typescript](https://github.com/zxbodya/flowts/blob/master/packages/babel-plugin-flow-to-typescript/src/visitors/Program.ts)

**Comment by meandmax** [comment]
Wow, yeah no idea why the search of github did not find this :D
