### ISSUE TITLE
Support for Flow enums in flowts

### ISSUE THREAD

**Issue by amyleecodes** [zxbodya/flowts#43]
Flow has support for enums: https://flow.org/en/docs/enums/

tsflow can properly convert Typescript enums to Flow enums, but flowts  will error with a babel parse error if it encounters a Flow enum.

Is this something on the roadmap or planned to be supported? Thanks!

**Comment by zxbodya** [comment]
Was not in the roadmap - codebases, I converted so far, did not had it.

Added support for it in https://github.com/zxbodya/flowts/commit/57217afad6c2159ac2a0837693ffcd447c869221, and just published a new version of flowts.

---

Let me know, if it works for you or if there are cases not supported yet.

**Comment by amyleecodes** [comment]
Apologies for the late reply on this– It worked perfectly. Thanks so much.
