### ISSUE TITLE
It messes up in-line parenthesized union types

### ISSUE THREAD

**Issue by nickretallack** [zxbodya/flowts#5]
If I run `flowts` on a file containing this:
```
export type t = ('a' | 'b')[]
```
It converts it to this:
```
export type t = 'a' | 'b'[];
```
This doesn't mean the same thing.

If I pass `--no-recast`, it leaves the code as is.

**Comment by zxbodya** [comment]
fixed in the latest release (fork of babel plugin and in flowts)

**Comment by nickretallack** [comment]
Thanks!

Though, I'd like to note that it now converts it to this when I pass `--no-prettier`:
```
export type t = ("a" | "b")[];
```
While passing `--no-recast` still causes it to leave the line alone.

Not terrible, but I'd have hoped that using recast would result in less changes, not more.

I get why it's happening though.  Despite the code looking identical, this is an AST change, right?

I'd feel more comfortable passing the `--prettier` option if I knew I could pin the version of prettier than flowts is using to be the same as the one in my project.

Also, should recast be taught to preserve the type of quotes used in the original code?
